#配置服务器
server:
  port: 8080
  servlet:
    context-path: /
#配置mysql数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_guides_sys?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
#配置mybatis xml文件路径
mybatis:
  mapper-locations:
  - classpath:mappers/sys/*.xml
  
logging:
  level:
    com.suse: debug